version: '3.8'

services:
  ordering-api:
    build:
      context: .
      dockerfile: src/Ordering.API/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
